### ISSUE TITLE
[TRACKING ISSUE] Improve Message Sending

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/New-Ringer-Server#103]
### Description
There is a problem with message sending on Ringer. If you have a poor connection and you send a longer message, sometimes the message will fail to send and be discarded. This forces the user to retype the message, which can be very frustrating.

### Solution 
Make a new system for sending messages. Here is the process.

1. The client will send a message to the server with a "SendTime" key in the data. This is the time the user hits the send button when typing the message.

2. After the message has been sent, there is a timeout period during which the client waits for an acknowledgment from the server that the message was sent. If the timeout exceeds and the server does not respond, the client will alert the user of the failure to send the message and ask to retry.

3. If the message does get to the server after the timeout exceeds, the server will check the send time and if it exceeds the timeout it will discard the message.

### Tasks

- [x] Lif-Platforms/Ringer-Client-Mobile#66
- [x] Lif-Platforms/Ringer-Client-Desktop#161
- [x] Lif-Platforms/Ringer-Client-Mobile#67
- [x] Lif-Platforms/Ringer-Client-Desktop#162
- [x] #108
