### ISSUE TITLE
Change How Friend Requests Are Handled/Stored [TRACKING ISSUE]

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/New-Ringer-Server#109]
### Description
The current way of handling friend requests has a few problems. First, the data is stored as JSON in the database. This should be changed to SQL entries in a separate table. Another problem is that users can send multiple requests to the same person. This means that multiple requests from the same person will show up in their notifications panel. And lastly, users can send friend requests to people they are already friends with.

### Soulution
Create a new system for handling friend requests by storing them in a friend requests table and making each friend request an entry in that table instead of storing them as JSON data. An update should be made that prohibits sending multiple friend requests to the same person as well as sending them to people they are already friends with. This new system should also allow users to see all outgoing friend requests and give them the option to cancel them if they have not already been accepted.

### Tasks

- [x] Lif-Platforms/New-Ringer-Server#125
- [x] Lif-Platforms/New-Ringer-Server#127
- [x] Lif-Platforms/Ringer-Client-Desktop#168
- [x] Lif-Platforms/Ringer-Client-Mobile#112
