### ISSUE TITLE
Dockize Ringer Server

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/New-Ringer-Server#31]
**Description**
Update Ringer Server to be able to be hosted with Docker. This will make updating Ringer Server much easier across our entire fleet of servers. Also, add a GitHub automation to automatically build and push new Docker images when a new release is created. 

**Tasks**

- [x] Update Ringer Server to work within a docker container
- [x] Create a Dockerfile for building images
- [x] Create a Public Docker Hub repo for Ringer Server
- [ ] Create a GitHub Automation to build and push new images on release
