### ISSUE TITLE
Dockerize Ringer Server

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/New-Ringer-Server#32]
Make Ringer server able to run in a production environment with docker. 

**Tasks**
- [ ] Create a Dockerfile for building the images
- [ ] Create a public Docker Hub repo for images. 
- [ ] Create an automation to build and push new images when a release is made
