### ISSUE TITLE
Dockerize Ringer Server

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/New-Ringer-Server#34]
Add support for Docker to Ringer Server. 

**Why Do This**
This will allow easier deployment of Ringer server in a couple of ways. 

1. It will make the environment that Ringer server runs in the same across all servers. 
2. It will make publishing new versions easier by allowing us to push updates to all of our servers automatically. 

**Tasks** 

- [ ] Prepare Ringer Server to work with Docker
- [ ] Create a Dockerfile for building Ringer Server images
- [ ] Create a public Docker Hub repo to push the images to
- [ ] Create a GitHub automation to automatically build and push an image when a new release is created
