### ISSUE TITLE
Dockerize Ringer Server

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/New-Ringer-Server#41]
Add Docker support to Ringer Server so that it can run inside a Docker container. 

### Tasks
- [x] Create Dockerfile for building images
- [x] Create Docker Hub repo for Ringer Server images
- [x] Create Github automation to build and push images to docker hub on release
