### ISSUE TITLE
Add Messaging Ability to Ringer

### ISSUE THREAD

**Issue by Superior126** [Lif-Platforms/New-Ringer-Server#5]
Add the ability to message users in Ringer.

**Tasks**

- [x] Add data table for messages
- [x] Add the ability to select a conversation from the friend's sidebar 
- [x] Add a system for sending messages to other users
- [ ] Make messages appear in the messages section
